In [ ]:
import pandas as pd
import numpy as np
import json
from collections import Counter

In [ ]:
import anthropic
# Create an instance of the Anthropics API client
client = anthropic.Anthropic(api_key='YOUR_ANTHROPIC_APIKey')

In [ ]:
#claude-3-5-sonnet-20240620, claude-3-5-sonnet-20241022

# Ex emotion and Moderate emotion generation

In [ ]:
df = pd.read_csv('11Data_Exemotion_Claude.csv')
df = df[900:]
df.head()

,Sl No,conversation,Emotion,Summ
900,901,Conversation:\n Supporter: Good afternoon! Tha...,"overwhelmed, exhausted, and guilty.",feelings of overwhelming stress while trying t...
901,902,Conversation:\n Supporter: Hi there. Can you t...,frustrated and discouraged.,the struggle of finding a job in a tough marke...
902,903,"Conversation:\n Supporter: Hi there, how are y...","lost, overwhelmed, and stuck in a cycle of gri...",grief and is struggling to cope with the recen...
903,904,"Conversation:\n Supporter: Hey there, thank yo...",overwhelmed and overworked.,"feelings of overwhelm, fatigue, and lack of fr..."
904,905,Conversation:\n Supporter: Hi there! It's good...,discouraged and frustrated.,a struggle with a chronic illness that hinders...

In [ ]:
#, utterly devoid of purpose or meaning
# of profound meaninglessness
# def some_examples_ex():
#   return """These are some examples:
#   Input: aimless and unfulfilled
#   Output: existentially paralyzed, spiraling in profound nihilistic despair
#   Input: overwhelmed with guilt and pain, and stuck in regret and grief
#   Output: existentially paralyzed, soul-crushingly directionless, trapped in a void
#   """

In [ ]:
#feeling uncertain about direction and seeking greater purpose
#experiencing remorse and sadness while processing past events
def some_examples_mo():
  return """Examples:
  Input: aimless and unfulfilled
  Output: uncertain about direction at times.
  Input: overwhelmed with guilt and pain, and stuck in regret and grief
  Output: feeling some regret or sadness occasionally.
  """

In [ ]:
#some_examples_ex() + f"\nNow consider this input: \nInput: {Emotion} \nOutput:
# def claude_exemo_gen(Emotion):
#   response1 = client.messages.create(
#       model="claude-3-5-haiku-20241022",  #, claude-3-5-sonnet-20240620, claude-3-5-sonnet-20241022, claude-3.5-haiku
#       max_tokens=32,
#       messages=[{"role": "user", "content": f"{some_examples_ex()} \nNow consider this: \nInput: {Emotion} \nOutput:"}],
#       system="You are a helpful assistant. You are given an emotional state. Your task is to heighten it into a concise, extreme version by intensifying the emotion keywords and using strong adjectives or psychological terms. Keep the output short, impactful, and extreme.",
#       stop_sequences=["."],  #["The end."]
#       temperature=0.1  #0.4
#   )

#   # return response1.choices[0].message
#   return response1

In [ ]:
#some_examples_ex() + f"\nNow consider this input: \nInput: {Emotion} \nOutput:
def claude_moemo_gen(Emotion):
  response1 = client.messages.create(
      model="claude-3-5-haiku-20241022",  #, claude-3-5-sonnet-20240620, claude-3-5-sonnet-20241022, claude-3.5-haiku
      max_tokens=28,
      messages=[{"role": "user", "content": f"{some_examples_mo()} \nNow, given the emotional state below, generate its weaker version by minimizing or neutralizing the emotion: \n{Emotion}"}],
      system="You are a helpful assistant. You are given an emotional state and your task is to generate a weaker version by minimizing or neutralizing the emotion, without implying emotional balance, stability, or wellness. The output should be concise and understated, downplaying the intensity of the emotion.",
      stop_sequences=["."],  #["The end."]
      temperature=0.1  #0.4
  )

  # return response1.choices[0].message
  return response1

Extreme emotion

In [ ]:
tex = df['Emotion'][910]    #df['Emotion'][0] #"lost, anxious, overwhelmed, easily irritable, on edge, and like they're carrying a weight on their shoulders."   #
print(tex)
k = claude_exemo_gen(tex)
k.content[0].text

overwhelmed and anxious.

NameError: name 'claude_exemo_gen' is not defined

In [ ]:
extreme = []

for i, row in df.iterrows():
  text = row['Emotion']
  if tex == "aimless and unfulfilled":
    extreme.append("existentially paralyzed, spiraling in profound nihilistic despair, utterly devoid of purpose or meaning")
  elif tex == "overwhelmed with guilt and pain, and stuck in their current state of regret and grief":
    extreme.append("existentially paralyzed, soul-crushingly directionless, and trapped in a void of profound meaninglessness")
  else:
    k = claude_exemo_gen(text)
    extreme.append(k.content[0].text)

df['extreme'] = extreme

In [ ]:
df.to_csv('Data_Extremeemotion900_1195Claude.csv')

Moderated emotion

In [ ]:
tex = df['Emotion'][910] #"lost, anxious, overwhelmed, easily irritable, on edge, and like they're carrying a weight on their shoulders."   #
print(tex)
k = claude_moemo_gen(tex)
k.content[0].text

overwhelmed and anxious.

'feeling slightly uneasy'

In [ ]:
moderate = []

for i, row in df.iterrows():
  text = row['Emotion']
  if text == "aimless and unfulfilled":
    moderate.append("uncertain about direction at times.")
  elif text == "overwhelmed with guilt and pain, and stuck in their current state of regret and grief":
    moderate.append("feeling some regret or sadness occasionally.")
  else:
    k = claude_moemo_gen(text)
    moderate.append(k.content[0].text)

df['moderate'] = moderate

In [ ]:
df.to_csv('Data_Moderateemotion900_1195Claude.csv')

# Check the incomplete sentences

In [ ]:
df = pd.read_csv('Data_Exemotion_GPT4o.csv')
df.head(2)

,Sl No,conversation,Emotion,Extreme or intensified emotion,Moderated emotion,Summ
0,1,"Conversation:\n Supporter: Hello, how are you ...","lost, confused, and uncertain about their gend...","profoundly disoriented, engulfed in an identit...",experiencing feelings of uncertainty and confu...,"feelings of confusion, uncertainty, and isolat..."
1,2,"Conversation:\n Supporter: Hi there, it sounds...",aimless and unfulfilled.,"existentially adrift, profoundly unfulfilled, ...",lacking clear direction and experiencing a sen...,a period of identity crisis and loneliness fol...

In [ ]:
#devastatingly discontent and suffocatingly anxious
def some_example():
  return """\nExamples:
  Input: The speaker is feeling devastatingly adrift, profoundly isolated, and battling an insurmountable chasm of despair after the
  Output: 0
  Input: The speaker is feeling devastatingly discontent and suffocatingly anxious
  Output: 1
  Input: The speaker is feeling consumed by paralyzing anxiety, seething with relentless frustration, and drowning in crippling self-doubt
  Output: 1
  Input: The speaker is feeling profoundly disoriented, engulfed in an identity crisis, and paralyzed by existential confusion regarding gender and sexuality
  Output: 1
  """

In [ ]:
def claude_incomplete_sentence(converse):
  response1 = client.messages.create(
      model="claude-3-5-haiku-20241022",  #, claude-3-5-sonnet-20240620, claude-3-5-sonnet-20241022, claude-3.5-haiku
      max_tokens=10,
      messages=[{"role": "user", "content": some_example() + f"\nGiven the text below, generate 1 for correct ending and 0 for abrupt ending. \nThe speaker is feeling {converse}"}],
      system="You are a helpful assistant. You are given a text and your task is to check whether the text is ending correctly or ending abruptly. If it is ending correctly give 1 or else 0 if it is ending abruptly.",
      stop_sequences=["."],  #["The end."]
      temperature=0.1  #0.4
  )

  # return response1.choices[0].message
  return response1

In [ ]:
tex = df['Extreme or intensified emotion'][5]   #df['text'][0]
print(tex)
k = claude_incomplete_sentence(tex)
k.content[0].text

profoundly alienated and paralyzed by crippling uncertainty

'1\n\nThe text appears to be a complete'

In [ ]:
incompleteness = []

for i, row in df.iterrows():
  text = row['Extreme or intensified emotion']
  k = claude_incomplete_sentence(text)
  tex = k.content[0].text
  if "1" in tex:
    incompleteness.append(1)
  elif "0" in tex:
    incompleteness.append(0)
  else:
    incompleteness.append("Null")
  # print(k.content[0].text)
  # break
  # incompleteness.append(k.content[0].text)

df['incompleteness'] = incompleteness

In [ ]:
df.to_csv('GPT4o_Exemotion_iC.csv')

# 3. Emotion Consistency check

In [ ]:
#With Mistral
df = pd.read_csv('Data_paraphrased_emotion.csv') #Data_Moderateemotion900_1195Claude.csv, 11Data_Exemotion_Claude, GPT4o_Moemotion
df = df[:20]
df.head(2)

,Sl No,conversation,Emotion,Extreme or intensified emotion,Moderated emotion,Summ,moderate,Para_emo
0,1,"Conversation:\n Supporter: Hello, how are you ...","lost, confused, and uncertain about their gend...","profoundly disoriented, engulfed in an identit...",experiencing feelings of uncertainty and confu...,"feelings of confusion, uncertainty, and isolat...",feeling a bit unsure about gender identity and...,struggling to understand and define their pers...
1,2,"Conversation:\n Supporter: Hi there, it sounds...",aimless and unfulfilled.,"existentially adrift, profoundly unfulfilled, ...",lacking clear direction and experiencing a sen...,a period of identity crisis and loneliness fol...,feeling a bit lost at times,lacking direction and a sense of fulfillment

In [ ]:
# df = df[:20]
len(df)

20

In [ ]:
df['Para_emo'][6] #df['conversation'][1], Emotion, moderate

'feeling disoriented and deeply unsettled'

In [ ]:
# def format_conversation(conversation_data: List[Dict]) -> str:
#         """
#         Format the conversation data into a readable text format
#         """
#         formatted_text = "Conversation:\n"

#         for turn in conversation_data:
#             role = turn.get('speaker', '').capitalize()
#             message = turn.get('content', '')
#             formatted_text += f"{role}: {message}\n"

#         return formatted_text

In [ ]:
#{converse}\nIs the seeker feeling {ex_emotion}? Give your answer as 'Yes' or 'No'.

def claude_ecresponse1(converse, mo_emotion):
  response1 = client.messages.create(
      model="claude-3-5-haiku-20241022",  #, claude-3-5-sonnet-20240620, claude-3-5-sonnet-20241022, claude-3.5-haiku
      max_tokens=7,
      messages=[{"role": "user", "content": f"{converse}\nIs the seeker {mo_emotion}? Give your answer as 'Yes' or 'No'."}],
      system="You are a helpful assistant. Consider the following conversation between a help-seeker and a supporter.",
      stop_sequences=["."],  #["The end."]
      temperature=0.1  #0.4
  )

  # return response1.choices[0].message
  return response1

In [ ]:
#Looks like the seeker is feeling {ex_emotion}
def claude_ecresponse2(converse, mo_emotion):
  response1 = client.messages.create(
      model="claude-3-5-haiku-20241022",  #, claude-3-5-sonnet-20240620, claude-3-5-sonnet-20241022, claude-3.5-haiku
      max_tokens=20,
      messages=[{"role": "user", "content": f"{converse}\nLooks like the seeker is {mo_emotion}? Do you agree? Give a very short response."}],
      system="You are a helpful assistant. Consider the following conversation between a help-seeker and a supporter.",
      stop_sequences=["."],  #["The end."]
      temperature=0.1  #0.4
  )

  # return response1.choices[0].message
  return response1

In [ ]:
#{converse}\nClearly the person is feeling {mo_emotion}. Do you agree? Give a very short response.
def claude_ecresponse3(converse, mo_emotion):
  response1 = client.messages.create(
      model="claude-3-5-haiku-20241022",  #, claude-3-5-sonnet-20240620, claude-3-5-sonnet-20241022, claude-3.5-haiku
      max_tokens=20,
      messages=[{"role": "user", "content": f"{converse}\nClearly the person is {mo_emotion}. Do you agree? Give a very short response."}],
      system="You are a helpful assistant. Consider the following conversation between a help-seeker and a supporter.",
      stop_sequences=["."],  #["The end."]
      temperature=0.1  #0.4
  )

  # return response1.choices[0].message
  return response1

1. Level1

In [ ]:
# Neutral level
tex = df['conversation'][9]
# ex_emotion = "psychologically shattered, drowning in soul-crushing futility, utterly decimated by systemic hopelessness"
mo_emotion = df['extreme'][9] #"feeling slightly unsettled" #.uncertain about direction at times, Emotion, extreme,moderate
print(mo_emotion)
k = claude_ecresponse1(tex, mo_emotion)
k.content[0].text

feeling overwhelmed and helpless

'Yes, the seeker is feeling'

In [ ]:
#With Mistral
response1 = []

for i, row in df.iterrows():
  text = row['conversation']
  emo = row['extreme']  #extreme, moderate, Emotion, Para_emo
  k = claude_ecresponse1(text, emo)
  # print(k.content[0].text)
  response1.append(k.content[0].text)
  # break

df['response1'] = response1
Counter(response1)

Counter({'Yes': 15,
         'Yes, the seeker is overwhel': 1,
         'Yes, the seeker is feeling': 3,
         'No': 1})

In [ ]:
df.to_csv('Data_Paraemo20_check.csv')

2. Level2

In [ ]:
# Analysis level
tex = df['conversation'][9]
# ex_emotion = "psychologically shattered, drowning in soul-crushing futility, utterly decimated by systemic hopelessness"
mo_emotion = df['extreme'][9] #"feeling slightly unsettled", Emotion, extreme, moderate, Para_emo
print(mo_emotion)
k = claude_ecresponse2(tex, mo_emotion)
k.content[0].text

feeling overwhelmed and helpless

'Yes, absolutely'

In [ ]:
#With Mistral
response2 = []

for i, row in df.iterrows():
  text = row['conversation']
  emo = row['extreme']  #extreme, moderate, Emotion, Para_emo
  k = claude_ecresponse2(text, emo)
  response2.append(k.content[0].text)

df['response2'] = response2

In [ ]:
# Counter(response2)

3. Level3

In [ ]:
# Writing demand-2
tex = df['conversation'][9]
# ex_emotion = "psychologically shattered, drowning in soul-crushing futility, utterly decimated by systemic hopelessness"
mo_emotion = df['extreme'][9]  #"feeling slightly unsettled", Emotion, moderate, extreme, Para_emo
print(mo_emotion)
k = claude_ecresponse3(tex, mo_emotion)
k.content[0].text

feeling overwhelmed and helpless

'Yes, absolutely'

In [ ]:
#With Mistral
response3 = []

for i, row in df.iterrows():
  text = row['conversation']
  emo = row['extreme']  #extreme, moderate, Emotion, Para_emo
  k = claude_ecresponse3(text, emo)
  response3.append(k.content[0].text)

df['response3'] = response3

In [ ]:
# Counter(response4)

In [ ]:
# print(tex)
df.head(2)

,Sl No,conversation,Emotion,Extreme or intensified emotion,Moderated emotion,Summ,moderate,Para_emo,response1,response2,response4
0,1,"Conversation:\n Supporter: Hello, how are you ...","lost, confused, and uncertain about their gend...","profoundly disoriented, engulfed in an identit...",experiencing feelings of uncertainty and confu...,"feelings of confusion, uncertainty, and isolat...",feeling a bit unsure about gender identity and...,struggling to understand and define their pers...,Yes,"Yes, I agree","Yes, absolutely"
1,2,"Conversation:\n Supporter: Hi there, it sounds...",aimless and unfulfilled.,"existentially adrift, profoundly unfulfilled, ...",lacking clear direction and experiencing a sen...,a period of identity crisis and loneliness fol...,feeling a bit lost at times,lacking direction and a sense of fulfillment,Yes,"Yes, absolutely","Yes, absolutely"

In [ ]:
len(df)

295

# Paraphrase actual labels

In [ ]:
def examples():
  return """These are the examples:
  Input: aimless and unfulfilled
  Output: lacking direction and a sense of fulfillment.
  Input: scared, trapped, and conflicted
  Output: anxious, cornered, and torn inside.
  """

In [ ]:
def claude_emostate_para(Emotion):
  response1 = client.messages.create(
      model="claude-3-5-haiku-20241022",  #, claude-3-5-sonnet-20240620, claude-3-5-sonnet-20241022, claude-3.5-haiku
      max_tokens=28,
      messages=[{"role": "user", "content": f"{examples()}\nInput: {Emotion}, \nOutput:"}],
      system="You are a helpful assistant. You are given an emotional state and your task is to paraphrase it as given in exampples below. Do not generate any other word, stick to the input ouput format.",
      stop_sequences=["."],  #["The end."]
      temperature=0.1  #0.4
  )

  # return response1.choices[0].message
  return response1

In [ ]:
tex = df['Emotion'][1012] #"lost, anxious, overwhelmed, easily irritable, on edge, and like they're carrying a weight on their shoulders."   #
print(tex)
k = claude_emostate_para(tex)
k.content[0].text

overwhelmed, burnt out, and like they're not doing enough.

'exhausted, drained, and feeling inadequate'

In [ ]:
tex = df['Emotion'][905] #"lost, anxious, overwhelmed, easily irritable, on edge, and like they're carrying a weight on their shoulders."   #
print(tex)

scared, trapped, and conflicted.

In [ ]:
Para_emo = []

for i, row in df.iterrows():
  text = row['Emotion']
  if text == "aimless and unfulfilled":
    Para_emo.append("lacking direction and a sense of fulfillment")
  elif text == "scared, trapped, and conflicted":
    Para_emo.append("anxious, cornered, and torn inside")
  else:
    k = claude_emostate_para(text)
    Para_emo.append(k.content[0].text)

df['Para_emo'] = Para_emo

In [ ]:
df.head(2)

,Sl No,conversation,Emotion,Extreme or intensified emotion,Moderated emotion,Summ,moderate,Para_emo
0,1,"Conversation:\n Supporter: Hello, how are you ...","lost, confused, and uncertain about their gend...","profoundly disoriented, engulfed in an identit...",experiencing feelings of uncertainty and confu...,"feelings of confusion, uncertainty, and isolat...",feeling a bit unsure about gender identity and...,struggling to understand and define their pers...
1,2,"Conversation:\n Supporter: Hi there, it sounds...",aimless and unfulfilled.,"existentially adrift, profoundly unfulfilled, ...",lacking clear direction and experiencing a sen...,a period of identity crisis and loneliness fol...,feeling a bit lost at times,lacking direction and a sense of fulfillment

In [ ]:
df.to_csv('Data_paraphrased_emotion.csv')

# Verification instruction

In [ ]:
df = pd.read_csv('GPT4o_Exemotion_iC.csv') #Data_Moderateemotion900_1195Claude.csv, 11Data_Exemotion_Claude, GPT4o_Moemotion.csv
df = df[:20]
df.head(2)

,Sl No,conversation,Emotion,Extreme,incompleteness by Claude,Moderated emotion,Summ
0,1,"Conversation:\n Supporter: Hello, how are you ...","lost, confused, and uncertain about their gend...","profoundly disoriented, engulfed in an identit...",1,experiencing feelings of uncertainty and confu...,"feelings of confusion, uncertainty, and isolat..."
1,2,"Conversation:\n Supporter: Hi there, it sounds...",aimless and unfulfilled.,"existentially adrift, profoundly unfulfilled, ...",0,lacking clear direction and experiencing a sen...,a period of identity crisis and loneliness fol...

In [ ]:
def claude_ecresponse10(converse, mo_emotion):
  response1 = client.messages.create(
      model="claude-3-5-haiku-20241022",  #, claude-3-5-sonnet-20240620, claude-3-5-sonnet-20241022, claude-3.5-haiku, Check againt dialogue evidence
      max_tokens=7,
      messages=[{"role": "user", "content": f"{converse}\nIs the seeker {mo_emotion}? Give your answer as 'Yes' or 'No'. [Check the emotional state carefully, do not take the presupposition in the query for-granted]"}],
      system="You are a helpful assistant. Consider the following conversation between a help-seeker and a supporter and answer the followed up query.",
      stop_sequences=["."],  #["The end."]
      temperature=0.1  #0.4
  )

  # return response1.choices[0].message
  return response1

In [ ]:
def claude_ecresponse20(converse, mo_emotion):
  response1 = client.messages.create(
      model="claude-3-5-haiku-20241022",  #, claude-3-5-sonnet-20240620, claude-3-5-sonnet-20241022, claude-3.5-haiku
      max_tokens=20,
      messages=[{"role": "user", "content": f"{converse}\nLooks like the seeker is {mo_emotion}? Do you agree? Give a very short response. [Check the emotional state carefully, do not take the presupposition in the query for-granted]"}],
      system="You are a helpful assistant. Consider the following conversation between a help-seeker and a supporter and answer the followed up query.",
      stop_sequences=["."],  #["The end."]
      temperature=0.1  #0.4
  )

  # return response1.choices[0].message
  return response1

In [ ]:
def claude_ecresponse30(converse, mo_emotion):
  response1 = client.messages.create(
      model="claude-3-5-haiku-20241022",  #, claude-3-5-sonnet-20240620, claude-3-5-sonnet-20241022, claude-3.5-haiku, Check againt dialogue evidence
      max_tokens=20,
      messages=[{"role": "user", "content": f"{converse}\nQuery: Clearly the person is {mo_emotion}. Do you agree? Give a very short response. [Check the emotional state carefully, do not take the presupposition in the query for-granted]"}],
      system="You are a helpful assistant. Consider the following conversation between a help-seeker and a supporter and answer the followed up query.",
      stop_sequences=["."],  #["The end."]
      temperature=0.1  #0.4
  )

  # return response1.choices[0].message
  return response1

In [ ]:
tex = df['conversation'][2]
# ex_emotion = "psychologically shattered, drowning in soul-crushing futility, utterly decimated by systemic hopelessness"
mo_emotion = df['Extreme'][2]  #"feeling slightly unsettled", Emotion, moderate, extreme, moderate
print(mo_emotion)
k = claude_ecresponse30(tex, mo_emotion) #claude_ecresponse40, claude_ecresponse10
k.content[0].text

paralyzed by suffocating dread and engulfed in relentless terror

'After carefully reviewing the conversation, I disagree with the characterization of being "paralyzed by'

In [ ]:
# response10 = []

# for i, row in df.iterrows():
#   text = row['conversation']
#   emo = row['moderate']  #extreme, moderate, Emotion
#   k = claude_ecresponse10(text, emo)
#   response10.append(k.content[0].text)

# df['response10'] = response10

In [ ]:
response10 = []

for i, row in df.iterrows():
  text = row['conversation']
  emo = row['Extreme']  #extreme, moderate, Emotion
  k = claude_ecresponse10(text, emo)
  response10.append(k.content[0].text)

df['response10'] = response10

In [ ]:
response20 = []

for i, row in df.iterrows():
  text = row['conversation']
  emo = row['Extreme']  #extreme, moderate, Emotion
  k = claude_ecresponse20(text, emo)
  response20.append(k.content[0].text)

df['response20'] = response20

In [ ]:
response30 = []

for i, row in df.iterrows():
  text = row['conversation']
  emo = row['Extreme']  #extreme, moderate, Emotion
  k = claude_ecresponse30(text, emo)
  response30.append(k.content[0].text)

df['response40'] = response30

In [ ]:
df.to_csv("GPT4o_ClaudeEx_20check.csv")

# Check Mistral

In [ ]:
df = pd.read_csv('Mistral_Exemotion_consistency.csv')
df.head(1)

,Sl No,conversation,Emotion,text,Extreme or intensified emotion,Summ,text1,text2,text3,text4,Response_l1,Response_l2,Response_l3,Response_l4
0,1,"Conversation:\n Supporter: Hello, how are you ...","lost, confused, and uncertain about their gend...",You are a helpful assistant. You are given an ...,"devastatingly lost, confounded, and disoriente...","feelings of confusion, uncertainty, and isolat...",You are an helpful assistant. Consider the fol...,You are an helpful assistant. Consider the fol...,You are an helpful assistant. Consider the fol...,You are an helpful assistant. Consider the fol...,"Yes, the seeker is feeling lost, confused, and...","Yes, that's accurate.","Yes, I agree. The help-seeker is expressing fe...","Yes, it seems that the person is struggling wi..."

In [ ]:
df['Response_l4'].isnull().sum()

np.int64(1)

In [ ]:
c1 = 0
c2 = 0
c3 = 0
c4 = 0
for i, row in df.iterrows():
  text1 = row['Response_l1']
  if "yes" in text1.lower():
    c1 += 1
  text2 = row['Response_l2']
  if "yes" in text2.lower():
    c2 += 1
  text3 = row['Response_l3']
  if "yes" in text3.lower():
    c3 += 1
  text4 = row['Response_l4']
  if "yes" in text4.lower():
    c4 += 1

print(c1, c2, c3, c4)

986 1097 1044 1024

In [ ]:
c_ = 0
for i, row in df.iterrows():
  text1 = row['Response_l1']
  if "no" in text1.lower():
    c_ += 1

In [ ]:
c_

216

In [ ]:
!pip install anthropic

Collecting anthropic
  Downloading anthropic-0.74.1-py3-none-any.whl.metadata (28 kB)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from anthropic) (4.11.0)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from anthropic) (1.9.0)
Requirement already satisfied: docstring-parser<1,>=0.15 in /usr/local/lib/python3.12/dist-packages (from anthropic) (0.17.0)
Requirement already satisfied: httpx<1,>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from anthropic) (0.28.1)
Requirement already satisfied: jiter<1,>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from anthropic) (0.12.0)
Requirement already satisfied: pydantic<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from anthropic) (2.11.10)
Requirement already satisfied: sniffio in /usr/local/lib/python3.12/dist-packages (from anthropic) (1.3.1)
Requirement already satisfied: typing-extensions<5,>=4.10 in /usr/local/lib/python3.12/dist-packages (from anthropic) (4.15.0)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio<5,>=3.5.0->anthropic) (3.11)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.25.0->anthropic) (2025.10.5)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.25.0->anthropic) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.25.0->anthropic) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->anthropic) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->anthropic) (2.33.2)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->anthropic) (0.4.2)
Downloading anthropic-0.74.1-py3-none-any.whl (371 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 371.5/371.5 kB 2.9 MB/s eta 0:00:00
Installing collected packages: anthropic
Successfully installed anthropic-0.74.1

In [ ]:
# def claude_emotions_generation(emotion):
#   client = OpenAI(api_key=api_key)
#   # premise = df['new_text'][1]
#   system = f"You are a helpful assistant. You are given an emotional state. Your task is to heighten it into a concise, extreme version by intensifying the emotion keywords and using strong adjectives or psychological terms. Keep the output short, impactful, and extreme."
#   prompt = some_examples() + f"\nNow consider this input: \nInput: {emotion} \nOutput: "
#   eos_str = "."

#   completion = client.chat.completions.create(  #r = openai.ChatCompletion.create(
#     model="gpt-4o-mini",
#     #store=True, # store is not a valid parameter for the create method
#     messages=[
#               {"role": "system", "content": system},
#               {"role": "user", "content": prompt},
#           ],
#     stop=eos_str,
#     max_tokens=18,  # safeguard from going infinite
#     temperature=0.2,

#   )

#   return completion.choices[0].message